name: SAST - Semgrep

on:
  push:
  pull_request:

permissions:
  contents: read
  security-events: write

jobs:
  semgrep:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar Semgrep
        run: |
          pip install --upgrade pip
          pip install semgrep

      - name: Rodar Semgrep (OWASP + NodeJS) e gerar SARIF/JSON
        run: |
          semgrep --config=p/owasp-top-ten --config=p/nodejsscan --metrics=off --sarif-output=semgrep.sarif || echo "{}" > semgrep.sarif
          semgrep --config=p/owasp-top-ten --config=p/nodejsscan --metrics=off --json  --output=semgrep.json  --error || echo "{}" > semgrep.json

      - name: Upload SARIF para GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif

      - name: Salvar relatórios como artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-reports
          path: |
            semgrep.sarif
            semgrep.json
